public class SampleClass {       //Class definition and body
   public static Integer myValue = 0;  //Class Member variable
   public static String myString = ''; //Class Member variable
   
   public static Integer getCalculatedValue () {
   // Method definition and body
   // do some calculation
      myValue = myValue+10;
      return myValue;
   }
}
//new line added one  mmore time and branches added here for sri
// added second line
// adding fourth line
// new line added on feb14
