name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push to the "feature" branch
  push:
    branches: ["feature"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runner's shell
      - name: Run a one-line script
        run: echo "Hello, world!"

      # Runs a set of commands using the runner's shell
      - name: Update code in dev branch
        run: |
          # Configure Git (if necessary)
          git config user.name "Kam-2"
          git config user.email "Kamal@cube84.com"

          # Check out the dev branch
          git fetch origin dev
          git checkout dev

          # Merge changes from feature branch to dev
          git merge origin/feature --no-ff -m "Merge changes from feature branch"

          # Push the updated dev branch back to the remote repository
          git push origin dev

      # Optional: Run additional build, test, or deploy steps here
      - name: Run additional build or test actions
        run: |
          echo "Add other actions to build, test, and deploy your project."
