name: CI

on:
  push:
    branches: [ "feature" ]

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v3
        with:
          ref: feature  

      - name: Set up Git
        run: |
          git config --global user.name "Kam-2"
          git config --global user.email "Kamal@cube84.com"

      - name: Fetch dev branch
        run: git fetch origin dev

      - name: Checkout dev branch
        run: git checkout dev

      - name: Merge feature branch into dev
        run: |
          git merge feature --no-ff --allow-unrelated-histories -m "Merge feature branch to dev"
          if [ -f "force-app/main/default/classes/SampleClass.cls" ]; then
            git checkout --ours force-app/main/default/classes/SampleClass.cls
            git add force-app/main/default/classes/SampleClass.cls
            git commit -m "Resolved merge conflict in SampleClass.cls"
          fi

      - name: Push changes to dev branch
        run: |
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
